# conda env create -f environment.yml
name: pbg-ld
channels:
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - numpy=1.16.4
  - pandas=0.25.1
  - matplotlib=3.1.1
  - pydot=1.4.1
  - requests=2.22.0
  - networkz=2.3
